---
- name: Check if node is installed
  shell: test -e {{ mosh_node_location }}
  register: node_check
  failed_when: node_check.rc == 2
  become: yes
  become_user: "{{ mosh_system_user }}"

- name: Download node
  shell: curl -sL https://deb.nodesource.com/setup_{{ mosh_node_version }} | sudo -E bash -
  become: True
  become_user: root
  args:
    warn: no
  when:
    - node_check.rc > 0

- name: Update apt cache
  apt:
    update_cache: true
  when:
    - node_check.rc > 0

- name: Install nodejs
  apt:
    name: nodejs
    state: latest
    update_cache: true
    cache_valid_time: 600
  when:
    - node_check.rc > 0

- name: Check if n is installed
  shell: test -e {{ mosh_node_location }}
  register: n_check
  failed_when: n_check.rc == 2
  become: yes
  become_user: "{{ mosh_system_user }}"

- name: Install n
  npm:
    name: 'n'
    global: yes
  become: True
  become_user: root
  when:
    - n_check.rc > 0
